# Enkel arbetsflöde för att distribuera statiskt innehåll till GitHub Pages
name: Deploy static content to Pages

on:
  # Körs vid push till standardgrenen
  push:
    branches: ["main"]

  # Möjliggör manuell körning av detta arbetsflöde från fliken Actions
  workflow_dispatch:

# Anger behörigheter för GITHUB_TOKEN för att tillåta distribution till GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Tillåt endast en samtidig distribution, hoppa över körningar som är köade mellan den pågående körningen och den senaste köade.
# Avbryt dock INTE pågående körningar eftersom vi vill tillåta att dessa produktionsdistributioner slutförs.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Enkel distributionsjobb eftersom vi bara distribuerar
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checka ut källkod
        uses: actions/checkout@v3
      - name: Konfigurera Pages
        uses: actions/configure-pages@v5
      - name: Ladda upp artefakt
        uses: actions/upload-pages-artifact@v3
        with:
          # Ladda upp hela förvaret
          path: '.'
      - name: Distribuera till GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
