jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug
        run: ls -R

      - name: Build project
        run: |
          # Lägg till byggkommandon här om du använder en byggprocess
          # npm install && npm run build
          
      - name: Debug
        run: ls -R

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # Eller ändra till 'build' om du bygger något

      - name: Debug
        run: ls -R
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages
